name: Ruby CI

# This GitHub Actions workflow is named "Ruby CI" and is
# triggered by push events on branches starting with "fix/" or
# "rel/", pull requests on the
#
# The workflow has a single job named "build" that runs on the
# latest version of Ubuntu. It uses a strategy matrix to run
# the job with different
#
# The steps in the job are as follows:
# 1. Checkout code using the actions/checkout@v4 action.
# 2. Set up the specified version of Ruby using the
#     ruby/setup-ruby@v1 action.
# 3. Install dependencies using Bundler. The Bundler version
#     is determined by the matrix variable.
# 4. Run the "try" command using bundle exec try. The
#     continue-on-error flag is set to true, allowing the
#     workflow to continue even if this step
#
# This workflow is designed for continuous integration of a
# Ruby project, ensuring that the code builds and dependencies
# are installed correctly.

on:
  push:
    branches:
      - fix/*
      - rel/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  build:
    # Can also be set to `self-hosted` if worker is running. Possible
    # issue when switching (or trying to run a mix of github-hosted
    # and self-hosted). All workflows in the repo stopped being queued
    # up after having a self-hosted worker registered and available
    # and then manually shutdown and removed. To the extent that open
    # PRs showed 0 checks at all (as though there were no workflow
    # yaml files at all). Adding a new workflow in a test branch
    # seemed to wake up the dragon and all was well in the world.
    #
    # Rubygems as of version 3.6.0 has dropped support for
    # Ruby 3.0. Fair enough!
    #
    # https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#breaking-changes
    #
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - ruby: '3.4'
            continue-on-error: true
            experimental: true

          - ruby: '3.3'

          - ruby: '3.2'

          - ruby: '3.1'

          - ruby: '3.0'
            continue-on-error: true
            bundler: latest
            rubygems: '3.5.23'

    # Make redis available for running the tryouts
    services:
      redis:
        image: redis:bookworm@sha256:e422889e156ebea83856b6ff973bfe0c86bce867d80def228044eeecf925592b
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 5
        ports:
          # https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers#running-jobs-in-containers
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:

      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        continue-on-error: ${{ matrix.continue-on-error || false }}
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems || 'latest' }}
          bundler: ${{ matrix.bundler || 'latest' }}
          # When the following is true, also run "bundle install",
          # and cache the result automatically. Ran into an issue
          # with the caching and multiple ruby version? See commit
          # message for this change.
          bundler-cache: false

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48 # v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Install dependencies (bundler ${{ matrix.bundler }})
        continue-on-error: ${{ matrix.continue-on-error || false }}
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tryouts
        continue-on-error: ${{ matrix.continue-on-error || false }}
        run: |
          bundle exec try -vf

      - name: Typecheck with Sorbet
        continue-on-error: ${{ matrix.continue-on-error || true }}
        run: |
          bundle exec srb tc

      - name: Rubocop
        continue-on-error: ${{ matrix.continue-on-error || true }}
        run: |
          bundle exec rubocop --config .rubocop.yml --format json --fail-level warning
